// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { ListAssetsData, ListAssetsResponses, ListAssetsErrors, DeleteAssetData, DeleteAssetResponses, GetAssetData, GetAssetResponses, SetAssetCustomFieldData, SetAssetCustomFieldResponses, ListAssetVersionsData, ListAssetVersionsResponses, GetAssetVersionData, GetAssetVersionResponses, UpdateAssetVersionData, UpdateAssetVersionResponses, GetAssetVersionDownloadUrlData, GetAssetVersionDownloadUrlResponses, AddAssetVersionTagData, AddAssetVersionTagResponses, DeleteAssetVersionTagData, DeleteAssetVersionTagResponses, ListAssetBoardsData, ListAssetBoardsResponses, ListBoardsData, ListBoardsResponses, CreateBoardData, CreateBoardResponses, DeleteBoardData, DeleteBoardResponses, GetBoardData, GetBoardResponses, UpdateBoardData, UpdateBoardResponses, SetBoardCustomFieldData, SetBoardCustomFieldResponses, AddAssetsToBoardData, AddAssetsToBoardResponses, RemoveAssetFromBoardData, RemoveAssetFromBoardResponses, ListBoardGuestsData, ListBoardGuestsResponses, AddBoardGuestData, AddBoardGuestResponses, RemoveBoardGuestData, RemoveBoardGuestResponses, UpdateBoardGuestData, UpdateBoardGuestResponses, ListCustomFieldsData, ListCustomFieldsResponses, CreateCustomFieldData, CreateCustomFieldResponses, CreateCustomFieldErrors, DeleteCustomFieldData, DeleteCustomFieldResponses, GetCustomFieldData, GetCustomFieldResponses, UpdateCustomFieldData, UpdateCustomFieldResponses, AddCustomFieldValueData, AddCustomFieldValueResponses, DeleteCustomFieldValueData, DeleteCustomFieldValueResponses, UpdateCustomFieldValueData, UpdateCustomFieldValueResponses, ListTagsData, ListTagsResponses, CreateTagData, CreateTagResponses, DeleteTagData, DeleteTagResponses, UpdateTagData, UpdateTagResponses, CreateUploadData, CreateUploadResponses, CreateUploadPartData, CreateUploadPartResponses, CompleteMultipartUploadData, CompleteMultipartUploadResponses, CreateImportData, CreateImportResponses, GetImportStatusData, GetImportStatusResponses, ListRolesData, ListRolesResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get a list of assets.
 */
export const listAssets = <ThrowOnError extends boolean = false>(options?: Options<ListAssetsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListAssetsResponses, ListAssetsErrors, ThrowOnError>({
        responseType: 'json',
        url: '/v1/assets',
        ...options
    });
};

/**
 * Delete an asset
 */
export const deleteAsset = <ThrowOnError extends boolean = false>(options: Options<DeleteAssetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteAssetResponses, unknown, ThrowOnError>({
        url: '/v1/assets/{assetId}',
        ...options
    });
};

/**
 * Get an asset
 */
export const getAsset = <ThrowOnError extends boolean = false>(options: Options<GetAssetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetAssetResponses, unknown, ThrowOnError>({
        url: '/v1/assets/{assetId}',
        ...options
    });
};

/**
 * Set custom field value(s) on an asset
 *
 * Body:
 * - values - an array of objects containing the id of the custom field value to set (used for single-select and multi-select)
 * - value - a string containing the value to set (used for plain-text and date)
 *
 * To unset a custom field on an asset, set the relevant property above to null
 *
 */
export const setAssetCustomField = <ThrowOnError extends boolean = false>(options: Options<SetAssetCustomFieldData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<SetAssetCustomFieldResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/assets/{assetId}/customfields/{customFieldId}',
        ...options
    });
};

/**
 * Get a list of asset versions associated with an asset.
 */
export const listAssetVersions = <ThrowOnError extends boolean = false>(options: Options<ListAssetVersionsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ListAssetVersionsResponses, unknown, ThrowOnError>({
        url: '/v1/assets/{assetId}/versions',
        ...options
    });
};

/**
 * Get an asset version associated with an asset, including metadata fields like `IPTC` and `EXIF`.
 */
export const getAssetVersion = <ThrowOnError extends boolean = false>(options: Options<GetAssetVersionData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetAssetVersionResponses, unknown, ThrowOnError>({
        url: '/v1/assets/{assetId}/versions/{versionId}',
        ...options
    });
};

/**
 * Update an asset version
 *
 * Body:
 * - title - the title of the version
 * - description - the description of the version
 *
 */
export const updateAssetVersion = <ThrowOnError extends boolean = false>(options: Options<UpdateAssetVersionData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateAssetVersionResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/assets/{assetId}/versions/{versionId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get the download URL of an asset version
 */
export const getAssetVersionDownloadUrl = <ThrowOnError extends boolean = false>(options: Options<GetAssetVersionDownloadUrlData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetAssetVersionDownloadUrlResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/assets/{assetId}/versions/{versionId}/download',
        ...options
    });
};

/**
 * Add one or more tags to an asset version
 *
 * Body:
 * - id - the id of the tag to add to the version
 *
 */
export const addAssetVersionTag = <ThrowOnError extends boolean = false>(options: Options<AddAssetVersionTagData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddAssetVersionTagResponses, unknown, ThrowOnError>({
        url: '/v1/assets/{assetId}/versions/{versionId}/tags',
        ...options
    });
};

/**
 * Delete a tag from an asset version
 */
export const deleteAssetVersionTag = <ThrowOnError extends boolean = false>(options: Options<DeleteAssetVersionTagData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteAssetVersionTagResponses, unknown, ThrowOnError>({
        url: '/v1/assets/{assetId}/versions/{versionId}/tags/{tagId}',
        ...options
    });
};

/**
 * Get the list of parent boards of an asset
 */
export const listAssetBoards = <ThrowOnError extends boolean = false>(options: Options<ListAssetBoardsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ListAssetBoardsResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/assets/{assetId}/boards',
        ...options
    });
};

/**
 * Get the list of boards defined in an Air workspace.
 */
export const listBoards = <ThrowOnError extends boolean = false>(options?: Options<ListBoardsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListBoardsResponses, unknown, ThrowOnError>({
        url: '/v1/boards',
        ...options
    });
};

/**
 * Create a board at the top-level of the workspace or as a child of another board
 *
 * Body:
 * - title - the title of the board
 * - description - the description of the board
 * - parentBoardId (optional) - the id of the parent board that this board will be a child of
 *
 */
export const createBoard = <ThrowOnError extends boolean = false>(options?: Options<CreateBoardData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<CreateBoardResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/boards',
        ...options
    });
};

/**
 * Delete a board and any assets that are only contained in this board or its direct descendant boards.
 */
export const deleteBoard = <ThrowOnError extends boolean = false>(options: Options<DeleteBoardData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteBoardResponses, unknown, ThrowOnError>({
        url: '/v1/boards/{boardId}',
        ...options
    });
};

/**
 * Get a board
 */
export const getBoard = <ThrowOnError extends boolean = false>(options: Options<GetBoardData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetBoardResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/boards/{boardId}',
        ...options
    });
};

/**
 * Update one or more properties on a board
 *
 * Body:
 * - title - the title of the board
 * - description - the description of the board
 * - parentBoardId - the parent board this board is a child of. null will move the board to the root.
 *
 */
export const updateBoard = <ThrowOnError extends boolean = false>(options: Options<UpdateBoardData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateBoardResponses, unknown, ThrowOnError>({
        url: '/v1/boards/{boardId}',
        ...options
    });
};

/**
 * Assign value(s) for a custom field on a board
 *
 * Body:
 * - values - a list of objects with the id of the value to be set on the board for the custom field (used with single-select and multi-select custom fields)
 * - value - the string value to be set for the custom field on the board (used with plain-text and date custom fields)
 *
 */
export const setBoardCustomField = <ThrowOnError extends boolean = false>(options: Options<SetBoardCustomFieldData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<SetBoardCustomFieldResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/boards/{boardId}/customfields/{customFieldId}',
        ...options
    });
};

/**
 * Associates one or more assets to a board
 *
 * Body:
 * - assetIds - an array of assetIds to associate with the board
 *
 */
export const addAssetsToBoard = <ThrowOnError extends boolean = false>(options: Options<AddAssetsToBoardData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddAssetsToBoardResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/boards/{boardId}/assets',
        ...options
    });
};

/**
 * Removes an asset from a board
 */
export const removeAssetFromBoard = <ThrowOnError extends boolean = false>(options: Options<RemoveAssetFromBoardData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<RemoveAssetFromBoardResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/boards/{boardId}/assets/{assetId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get the list of guests of the board.
 */
export const listBoardGuests = <ThrowOnError extends boolean = false>(options: Options<ListBoardGuestsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ListBoardGuestsResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/boards/{boardId}/guests',
        ...options
    });
};

/**
 * Add a guest to the board.
 *
 * Body:
 * - email - email address of the user to be added as guest
 * - roleId - id of the role to be associated with the guest
 *
 */
export const addBoardGuest = <ThrowOnError extends boolean = false>(options: Options<AddBoardGuestData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddBoardGuestResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/boards/{boardId}/guests',
        ...options
    });
};

/**
 * Remove a guest from the board.
 */
export const removeBoardGuest = <ThrowOnError extends boolean = false>(options: Options<RemoveBoardGuestData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<RemoveBoardGuestResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/boards/{boardId}/guests/{guestId}',
        ...options
    });
};

/**
 * Change the role of a guest.
 *
 * Body:
 * - roleId - id of the role to be associated with the guest
 *
 */
export const updateBoardGuest = <ThrowOnError extends boolean = false>(options: Options<UpdateBoardGuestData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateBoardGuestResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/boards/{boardId}/guests/{guestId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List custom fields
 */
export const listCustomFields = <ThrowOnError extends boolean = false>(options?: Options<ListCustomFieldsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListCustomFieldsResponses, unknown, ThrowOnError>({
        url: '/v1/customfields',
        ...options
    });
};

/**
 * Create a custom field (maximum total allowed per workspace: 100)
 *
 * Body:
 * - name - the name of the custom field
 * - description - the description of the custom field
 * - type - the type of the custom field
 * - values - the values of a single-select or multi-select custom field
 *
 */
export const createCustomField = <ThrowOnError extends boolean = false>(options?: Options<CreateCustomFieldData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<CreateCustomFieldResponses, CreateCustomFieldErrors, ThrowOnError>({
        responseType: 'json',
        url: '/v1/customfields',
        ...options
    });
};

/**
 * Delete a custom field
 */
export const deleteCustomField = <ThrowOnError extends boolean = false>(options: Options<DeleteCustomFieldData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteCustomFieldResponses, unknown, ThrowOnError>({
        url: '/v1/customfields/{customFieldId}',
        ...options
    });
};

/**
 * Get a custom field
 */
export const getCustomField = <ThrowOnError extends boolean = false>(options: Options<GetCustomFieldData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCustomFieldResponses, unknown, ThrowOnError>({
        url: '/v1/customfields/{customFieldId}',
        ...options
    });
};

/**
 * Update one or more properties on a custom field
 *
 * Body:
 * - name - the name of the custom field
 * - description - the description of the custom field
 *
 * *type is immutable due to workflows being built on top of custom fields
 *
 */
export const updateCustomField = <ThrowOnError extends boolean = false>(options: Options<UpdateCustomFieldData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateCustomFieldResponses, unknown, ThrowOnError>({
        url: '/v1/customfields/{customFieldId}',
        ...options
    });
};

/**
 * Add a new value to a single-select or multi-select custom field.
 *
 * Body:
 * - name - the name of the custom field value
 *
 */
export const addCustomFieldValue = <ThrowOnError extends boolean = false>(options: Options<AddCustomFieldValueData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddCustomFieldValueResponses, unknown, ThrowOnError>({
        url: '/v1/customfields/{customFieldId}/values',
        ...options
    });
};

/**
 * Delete a value off of a custom field
 */
export const deleteCustomFieldValue = <ThrowOnError extends boolean = false>(options: Options<DeleteCustomFieldValueData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteCustomFieldValueResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/customfields/{customFieldId}/values/{valueId}',
        ...options
    });
};

/**
 * Update one or more properties on a value
 */
export const updateCustomFieldValue = <ThrowOnError extends boolean = false>(options: Options<UpdateCustomFieldValueData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateCustomFieldValueResponses, unknown, ThrowOnError>({
        url: '/v1/customfields/{customFieldId}/values/{valueId}',
        ...options
    });
};

/**
 * List tags in the workspace
 */
export const listTags = <ThrowOnError extends boolean = false>(options?: Options<ListTagsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListTagsResponses, unknown, ThrowOnError>({
        url: '/v1/tags',
        ...options
    });
};

/**
 * Create a new tag
 *
 * Body:
 * - name - the name of the tag
 *
 */
export const createTag = <ThrowOnError extends boolean = false>(options?: Options<CreateTagData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<CreateTagResponses, unknown, ThrowOnError>({
        url: '/v1/tags',
        ...options
    });
};

/**
 * Delete a tag
 */
export const deleteTag = <ThrowOnError extends boolean = false>(options: Options<DeleteTagData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteTagResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/tags/{tagId}',
        ...options
    });
};

/**
 * Update one or more properties on a tag
 */
export const updateTag = <ThrowOnError extends boolean = false>(options: Options<UpdateTagData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateTagResponses, unknown, ThrowOnError>({
        url: '/v1/tags/{tagId}',
        ...options
    });
};

/**
 * Upload an asset to a workspace
 *
 * Body:
 * - fileName - the name of the file
 * - ext - the extension of the file
 * - size - the size of the file
 * - mime - the mime of the file
 * - recordedAt - when the file was created
 * - parentBoardId (optional) - the parent board to create the asset under
 * - assetId (optional) - the parent asset to create a new version for this file under
 * - customFields (optional) - the list of custom fields and values to assign to the asset
 * - tags (optional) - the list of tags to assign to the asset version
 *
 */
export const createUpload = <ThrowOnError extends boolean = false>(options?: Options<CreateUploadData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<CreateUploadResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/uploads',
        ...options
    });
};

/**
 * Create a part upload url
 *
 * Body:
 * - multiPartUploadId - upload id returned from POST /uploads
 * - key - key returned from POST /uploads
 * - partNumber - the number associated with the chunk being uploaded
 *
 */
export const createUploadPart = <ThrowOnError extends boolean = false>(options?: Options<CreateUploadPartData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<CreateUploadPartResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/uploads/uploadPart',
        ...options
    });
};

/**
 * Complete a large file upload
 *
 * Body:
 * - multiPartUploadId - the upload id returned from POST /uploads
 * - key - the key returned from POST /uploads
 * - parts - an array of objects containing the etag (returned from file upload) and partNumber for each chunk
 *
 */
export const completeMultipartUpload = <ThrowOnError extends boolean = false>(options?: Options<CompleteMultipartUploadData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<CompleteMultipartUploadResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/completeMultipart',
        ...options
    });
};

/**
 * Create an import of an asset or asset version from a public URL.
 *
 * Request Body:
 * - sourceUrl - the URL to get the file content. The URL needs to be publicly accessible.
 * - fileName (optional) - the name of the file. If not provided then it will be determined from the URL.
 * - ext (optional) - the extension of the file. If not provided then the ext will be pulled from the URL or defaulted to .file
 * - recordedAt (optional) - when the file was created. If not provided the servers current time will be used.
 * - assetId (optional) - the parent asset to create a new version for this file under.
 * - parentBoardId (optional) - the parent board to create the asset under.
 * - customFields (optional) - the list of custom fields and values to assign to the asset.
 * - tags (optional) - the list of tags to assign to the asset version.
 * - title (optional) - the title to assign to the asset version.
 * - description (optional) - the description to assign to the asset version.
 *
 */
export const createImport = <ThrowOnError extends boolean = false>(options?: Options<CreateImportData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<CreateImportResponses, unknown, ThrowOnError>({
        url: '/v1/imports',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Retrieve the status of a specific import by providing the import ID in the URL.
 *
 * Response:
 * The body of the response will contain a JSON object with "status" and also "error" if the import is failed.
 * - status:
 * - pending - the import is waiting to be scheduled.
 * - inProgress - the import is in progress.
 * - failed - the import has failed.
 * - succeeded - the import completed.
 * - error: An object containing the error type and message if the import failed.
 * - SOURCE_FILE_NOT_FOUND - the file is not found from source Url when executing task.
 * - SOURCE_URL_BLOCKED - the source URL is to be blocked by the block rules.
 * - SOURCE_URL_INVALID - the file URL returns 4xx, 5xx errors.
 * - PROCESS_TIMED_OUT - exceeded the maximum amount of time allowed
 *
 */
export const getImportStatus = <ThrowOnError extends boolean = false>(options: Options<GetImportStatusData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetImportStatusResponses, unknown, ThrowOnError>({
        url: '/v1/imports/{importId}/status',
        ...options
    });
};

/**
 * Get the list of guest roles available in a workspace.
 */
export const listRoles = <ThrowOnError extends boolean = false>(options?: Options<ListRolesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListRolesResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/v1/roles',
        ...options
    });
};