"use strict";
// This file is auto-generated by @hey-api/openapi-ts
Object.defineProperty(exports, "__esModule", { value: true });
exports.getV1Roles = exports.getV1ImportsByImportIdStatus = exports.postV1Imports = exports.postV1CompleteMultipart = exports.postV1UploadsUploadPart = exports.postV1Uploads = exports.patchV1TagsByTagId = exports.deleteV1TagsByTagId = exports.postV1Tags = exports.getV1Tags = exports.patchV1CustomfieldsByCustomFieldIdValuesByValueId = exports.deleteV1CustomfieldsByCustomFieldIdValuesByValueId = exports.postV1CustomfieldsByCustomFieldIdValues = exports.patchV1CustomfieldsByCustomFieldId = exports.getV1CustomfieldsByCustomFieldId = exports.deleteV1CustomfieldsByCustomFieldId = exports.postV1Customfields = exports.getV1Customfields = exports.patchV1BoardsByBoardIdGuestsByGuestId = exports.deleteV1BoardsByBoardIdGuestsByGuestId = exports.postV1BoardsByBoardIdGuests = exports.getV1BoardsByBoardIdGuests = exports.deleteV1BoardsByBoardIdAssetsByAssetId = exports.postV1BoardsByBoardIdAssets = exports.putV1BoardsByBoardIdCustomfieldsByCustomFieldId = exports.patchV1BoardsByBoardId = exports.getV1BoardsByBoardId = exports.deleteV1BoardsByBoardId = exports.postV1Boards = exports.getV1Boards = exports.getV1AssetsByAssetIdBoards = exports.deleteV1AssetsByAssetIdVersionsByVersionIdTagsByTagId = exports.postV1AssetsByAssetIdVersionsByVersionIdTags = exports.getV1AssetsByAssetIdVersionsByVersionIdDownload = exports.patchV1AssetsByAssetIdVersionsByVersionId = exports.getAssetVersion = exports.getV1AssetsByAssetIdVersions = exports.putV1AssetsByAssetIdCustomfieldsByCustomFieldId = exports.getV1AssetsByAssetId = exports.deleteV1AssetsByAssetId = exports.getV1Assets = void 0;
const client_gen_1 = require("./client.gen");
/**
 * /assets
 */
const getV1Assets = (options) => {
    return (options?.client ?? client_gen_1.client).get({
        responseType: 'json',
        url: '/v1/assets',
        ...options
    });
};
exports.getV1Assets = getV1Assets;
/**
 * /assets/:assetId
 */
const deleteV1AssetsByAssetId = (options) => {
    return (options.client ?? client_gen_1.client).delete({
        url: '/v1/assets/{assetId}',
        ...options
    });
};
exports.deleteV1AssetsByAssetId = deleteV1AssetsByAssetId;
/**
 * /assets/:assetId
 */
const getV1AssetsByAssetId = (options) => {
    return (options.client ?? client_gen_1.client).get({
        url: '/v1/assets/{assetId}',
        ...options
    });
};
exports.getV1AssetsByAssetId = getV1AssetsByAssetId;
/**
 * /assets/:assetId/customfields/:customFieldId
 */
const putV1AssetsByAssetIdCustomfieldsByCustomFieldId = (options) => {
    return (options.client ?? client_gen_1.client).put({
        responseType: 'json',
        url: '/v1/assets/{assetId}/customfields/{customFieldId}',
        ...options
    });
};
exports.putV1AssetsByAssetIdCustomfieldsByCustomFieldId = putV1AssetsByAssetIdCustomfieldsByCustomFieldId;
const getV1AssetsByAssetIdVersions = (options) => {
    return (options.client ?? client_gen_1.client).get({
        url: '/v1/assets/{assetId}/versions',
        ...options
    });
};
exports.getV1AssetsByAssetIdVersions = getV1AssetsByAssetIdVersions;
/**
 * Get an asset version associated with an asset, including metadata fields like `IPTC` and `EXIF`.
 */
const getAssetVersion = (options) => {
    return (options.client ?? client_gen_1.client).get({
        url: '/v1/assets/{assetId}/versions/{versionId}',
        ...options
    });
};
exports.getAssetVersion = getAssetVersion;
/**
 * /assets/:assetId/versions/:versionId
 */
const patchV1AssetsByAssetIdVersionsByVersionId = (options) => {
    return (options.client ?? client_gen_1.client).patch({
        responseType: 'json',
        url: '/v1/assets/{assetId}/versions/{versionId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
exports.patchV1AssetsByAssetIdVersionsByVersionId = patchV1AssetsByAssetIdVersionsByVersionId;
/**
 * /assets/:assetId/versions/:versionId/download
 */
const getV1AssetsByAssetIdVersionsByVersionIdDownload = (options) => {
    return (options.client ?? client_gen_1.client).get({
        responseType: 'json',
        url: '/v1/assets/{assetId}/versions/{versionId}/download',
        ...options
    });
};
exports.getV1AssetsByAssetIdVersionsByVersionIdDownload = getV1AssetsByAssetIdVersionsByVersionIdDownload;
/**
 * /assets/:assetId/versions/:versionId/tags
 */
const postV1AssetsByAssetIdVersionsByVersionIdTags = (options) => {
    return (options.client ?? client_gen_1.client).post({
        url: '/v1/assets/{assetId}/versions/{versionId}/tags',
        ...options
    });
};
exports.postV1AssetsByAssetIdVersionsByVersionIdTags = postV1AssetsByAssetIdVersionsByVersionIdTags;
/**
 * /assets/:assetId/versions/:versionId/tags/:tagId
 */
const deleteV1AssetsByAssetIdVersionsByVersionIdTagsByTagId = (options) => {
    return (options.client ?? client_gen_1.client).delete({
        url: '/v1/assets/{assetId}/versions/{versionId}/tags/{tagId}',
        ...options
    });
};
exports.deleteV1AssetsByAssetIdVersionsByVersionIdTagsByTagId = deleteV1AssetsByAssetIdVersionsByVersionIdTagsByTagId;
/**
 * /assets/:assetId/boards
 */
const getV1AssetsByAssetIdBoards = (options) => {
    return (options.client ?? client_gen_1.client).get({
        responseType: 'json',
        url: '/v1/assets/{assetId}/boards',
        ...options
    });
};
exports.getV1AssetsByAssetIdBoards = getV1AssetsByAssetIdBoards;
/**
 * /boards
 */
const getV1Boards = (options) => {
    return (options?.client ?? client_gen_1.client).get({
        url: '/v1/boards',
        ...options
    });
};
exports.getV1Boards = getV1Boards;
/**
 * /boards
 */
const postV1Boards = (options) => {
    return (options?.client ?? client_gen_1.client).post({
        responseType: 'json',
        url: '/v1/boards',
        ...options
    });
};
exports.postV1Boards = postV1Boards;
/**
 * /boards/:boardId
 */
const deleteV1BoardsByBoardId = (options) => {
    return (options.client ?? client_gen_1.client).delete({
        url: '/v1/boards/{boardId}',
        ...options
    });
};
exports.deleteV1BoardsByBoardId = deleteV1BoardsByBoardId;
/**
 * /boards/:boardId
 */
const getV1BoardsByBoardId = (options) => {
    return (options.client ?? client_gen_1.client).get({
        responseType: 'json',
        url: '/v1/boards/{boardId}',
        ...options
    });
};
exports.getV1BoardsByBoardId = getV1BoardsByBoardId;
/**
 * /boards/:boardId
 */
const patchV1BoardsByBoardId = (options) => {
    return (options.client ?? client_gen_1.client).patch({
        url: '/v1/boards/{boardId}',
        ...options
    });
};
exports.patchV1BoardsByBoardId = patchV1BoardsByBoardId;
/**
 * /boards/:boardId/customfields/:customFieldId
 */
const putV1BoardsByBoardIdCustomfieldsByCustomFieldId = (options) => {
    return (options.client ?? client_gen_1.client).put({
        responseType: 'json',
        url: '/v1/boards/{boardId}/customfields/{customFieldId}',
        ...options
    });
};
exports.putV1BoardsByBoardIdCustomfieldsByCustomFieldId = putV1BoardsByBoardIdCustomfieldsByCustomFieldId;
/**
 * /boards/:boardId/assets
 */
const postV1BoardsByBoardIdAssets = (options) => {
    return (options.client ?? client_gen_1.client).post({
        responseType: 'json',
        url: '/v1/boards/{boardId}/assets',
        ...options
    });
};
exports.postV1BoardsByBoardIdAssets = postV1BoardsByBoardIdAssets;
/**
 * /boards/:boardId/assets/:assetId
 */
const deleteV1BoardsByBoardIdAssetsByAssetId = (options) => {
    return (options.client ?? client_gen_1.client).delete({
        responseType: 'json',
        url: '/v1/boards/{boardId}/assets/{assetId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
exports.deleteV1BoardsByBoardIdAssetsByAssetId = deleteV1BoardsByBoardIdAssetsByAssetId;
/**
 * /boards/:boardId/guests
 */
const getV1BoardsByBoardIdGuests = (options) => {
    return (options.client ?? client_gen_1.client).get({
        responseType: 'json',
        url: '/v1/boards/{boardId}/guests',
        ...options
    });
};
exports.getV1BoardsByBoardIdGuests = getV1BoardsByBoardIdGuests;
/**
 * /boards/:boardId/guests
 */
const postV1BoardsByBoardIdGuests = (options) => {
    return (options.client ?? client_gen_1.client).post({
        responseType: 'json',
        url: '/v1/boards/{boardId}/guests',
        ...options
    });
};
exports.postV1BoardsByBoardIdGuests = postV1BoardsByBoardIdGuests;
/**
 * /boards/:boardId/guests/:guestId
 */
const deleteV1BoardsByBoardIdGuestsByGuestId = (options) => {
    return (options.client ?? client_gen_1.client).delete({
        responseType: 'json',
        url: '/v1/boards/{boardId}/guests/{guestId}',
        ...options
    });
};
exports.deleteV1BoardsByBoardIdGuestsByGuestId = deleteV1BoardsByBoardIdGuestsByGuestId;
/**
 * /boards/:boardId/guests/:guestId
 */
const patchV1BoardsByBoardIdGuestsByGuestId = (options) => {
    return (options.client ?? client_gen_1.client).patch({
        responseType: 'json',
        url: '/v1/boards/{boardId}/guests/{guestId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
exports.patchV1BoardsByBoardIdGuestsByGuestId = patchV1BoardsByBoardIdGuestsByGuestId;
/**
 * /customfields
 */
const getV1Customfields = (options) => {
    return (options?.client ?? client_gen_1.client).get({
        url: '/v1/customfields',
        ...options
    });
};
exports.getV1Customfields = getV1Customfields;
/**
 * /customfields
 */
const postV1Customfields = (options) => {
    return (options?.client ?? client_gen_1.client).post({
        responseType: 'json',
        url: '/v1/customfields',
        ...options
    });
};
exports.postV1Customfields = postV1Customfields;
/**
 * /customfields/:customFieldId:
 */
const deleteV1CustomfieldsByCustomFieldId = (options) => {
    return (options.client ?? client_gen_1.client).delete({
        url: '/v1/customfields/{customFieldId}',
        ...options
    });
};
exports.deleteV1CustomfieldsByCustomFieldId = deleteV1CustomfieldsByCustomFieldId;
/**
 * /customfields/:customFieldId
 */
const getV1CustomfieldsByCustomFieldId = (options) => {
    return (options.client ?? client_gen_1.client).get({
        url: '/v1/customfields/{customFieldId}',
        ...options
    });
};
exports.getV1CustomfieldsByCustomFieldId = getV1CustomfieldsByCustomFieldId;
/**
 * /customfields/:customFieldId:
 */
const patchV1CustomfieldsByCustomFieldId = (options) => {
    return (options.client ?? client_gen_1.client).patch({
        url: '/v1/customfields/{customFieldId}',
        ...options
    });
};
exports.patchV1CustomfieldsByCustomFieldId = patchV1CustomfieldsByCustomFieldId;
/**
 * /customfields/:customFieldId:/values
 */
const postV1CustomfieldsByCustomFieldIdValues = (options) => {
    return (options.client ?? client_gen_1.client).post({
        url: '/v1/customfields/{customFieldId}/values',
        ...options
    });
};
exports.postV1CustomfieldsByCustomFieldIdValues = postV1CustomfieldsByCustomFieldIdValues;
/**
 * /customfields/:customFieldId:/values/:valueId
 */
const deleteV1CustomfieldsByCustomFieldIdValuesByValueId = (options) => {
    return (options.client ?? client_gen_1.client).delete({
        responseType: 'json',
        url: '/v1/customfields/{customFieldId}/values/{valueId}',
        ...options
    });
};
exports.deleteV1CustomfieldsByCustomFieldIdValuesByValueId = deleteV1CustomfieldsByCustomFieldIdValuesByValueId;
/**
 * /customfields/:customFieldId:/values/:valueId
 */
const patchV1CustomfieldsByCustomFieldIdValuesByValueId = (options) => {
    return (options.client ?? client_gen_1.client).patch({
        url: '/v1/customfields/{customFieldId}/values/{valueId}',
        ...options
    });
};
exports.patchV1CustomfieldsByCustomFieldIdValuesByValueId = patchV1CustomfieldsByCustomFieldIdValuesByValueId;
/**
 * /tags
 */
const getV1Tags = (options) => {
    return (options?.client ?? client_gen_1.client).get({
        url: '/v1/tags',
        ...options
    });
};
exports.getV1Tags = getV1Tags;
/**
 * /tags
 */
const postV1Tags = (options) => {
    return (options?.client ?? client_gen_1.client).post({
        url: '/v1/tags',
        ...options
    });
};
exports.postV1Tags = postV1Tags;
/**
 * /tags/:tagId
 */
const deleteV1TagsByTagId = (options) => {
    return (options.client ?? client_gen_1.client).delete({
        responseType: 'json',
        url: '/v1/tags/{tagId}',
        ...options
    });
};
exports.deleteV1TagsByTagId = deleteV1TagsByTagId;
/**
 * /tags/:tagId
 */
const patchV1TagsByTagId = (options) => {
    return (options.client ?? client_gen_1.client).patch({
        url: '/v1/tags/{tagId}',
        ...options
    });
};
exports.patchV1TagsByTagId = patchV1TagsByTagId;
/**
 * /uploads
 */
const postV1Uploads = (options) => {
    return (options?.client ?? client_gen_1.client).post({
        responseType: 'json',
        url: '/v1/uploads',
        ...options
    });
};
exports.postV1Uploads = postV1Uploads;
/**
 * uploads/uploadPart
 */
const postV1UploadsUploadPart = (options) => {
    return (options?.client ?? client_gen_1.client).post({
        responseType: 'json',
        url: '/v1/uploads/uploadPart',
        ...options
    });
};
exports.postV1UploadsUploadPart = postV1UploadsUploadPart;
/**
 * uploads/completeMultipart
 */
const postV1CompleteMultipart = (options) => {
    return (options?.client ?? client_gen_1.client).post({
        responseType: 'json',
        url: '/v1/completeMultipart',
        ...options
    });
};
exports.postV1CompleteMultipart = postV1CompleteMultipart;
/**
 * /imports
 */
const postV1Imports = (options) => {
    return (options?.client ?? client_gen_1.client).post({
        url: '/v1/imports',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};
exports.postV1Imports = postV1Imports;
/**
 * /imports/:importId/status
 */
const getV1ImportsByImportIdStatus = (options) => {
    return (options.client ?? client_gen_1.client).get({
        url: '/v1/imports/{importId}/status',
        ...options
    });
};
exports.getV1ImportsByImportIdStatus = getV1ImportsByImportIdStatus;
/**
 * /roles
 */
const getV1Roles = (options) => {
    return (options?.client ?? client_gen_1.client).get({
        responseType: 'json',
        url: '/v1/roles',
        ...options
    });
};
exports.getV1Roles = getV1Roles;
